### ISSUE TITLE
简易弹幕后端储存调用可以使用 SQLite 用node,js太高大上了，大部分应该人都不知道怎么部署

### ISSUE THREAD

**Issue by wst8023** [MoePlayer/DPlayer-WordPress#13]
如果可以像之前的mukioplay那样就方便多了

**Comment by wst8023** [comment]
WordPress用户来说，最好都是可以在一个插件内实现。
需要额外的程序辅助才能实现，那么相对来说不是很方便了。
WordPress用户非常多，能找到这个插件的都是为了弹幕功能。
希望大神可以完善一下，最好是安装上去就可以用。

**Comment by BlueCocoa** [comment]
现在就是安装好就可以用，@DIYgod 有公共服务器的，默认也是配置好了的
